=== ElectroNick-Pro/SoftwareEngineering2022-103/src/MainApp/config/config_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dataDir" type="xs:string"/>
                <xs:element name="datetimeFormat">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="timeStrFormat" type="xs:string"/>
                            <xs:element name="timeZone" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="userModel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="model" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="digest-algorithm" type="xs:string"/>
                <xs:element name="welcomePage" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ElectroNick-Pro/SoftwareEngineering2022-103/src/MainApp/config/config_template.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="config_schema.xsd">

    <dataDir>/</dataDir>

    <datetimeFormat>
        <timeStrFormat>yyyy-MM-dd HH:mm:ss</timeStrFormat>
        <timeZone>UTC</timeZone>
    </datetimeFormat>

    <userModel>
        <model>Airline</model>
        <model>Customer</model>
        <model>Flight</model>
        <model>Food</model>
        <model>Interval</model>
        <model>Plane</model>
        <model>Seat</model>
        <model>Ticket</model>
    </userModel>

    <welcomePage>page1</welcomePage>
    
</config>
